name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          check-latest: true
      - name: Setup Go Caches
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-test-
      - name: Run Tests
        run: |
          go mod download
          go test ./... -v -race
  gosec-test:
    name: GoSec Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run GoSec
        uses: securego/gosec@master
  govulncheck-test:
    name: GoVulnCheck Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Govulncheck
        uses: kmulvey/govulncheck-action@v1.0.0
        with:
          fail-on-vuln: true
